algoritmo exercise_01
    inteiro quantity
    literal name, position
    início
        escreva("Informe o nome: ")
        leia(name)
        escreva("Informe a quantidade de dependentes: ")
        leia(quantity)
        escreva("Informe o cargo: ")
        leia(position)
        escreva("O funcionario " + name + " que exerce o cargo de " + position + " tem " + quantity + " dependentes.")
    fim
